[manifest]
id = "z_targeting_suite"
version = "1.0.0"
display_name = "Z-Targeting Suite"
description = """
A collection of tweaks to modernize and customize Z-Targeting mechanics.

Features include:
- Immersive Targeting: Removes non-diegetic visual and audio cues.
- 360-Degree Lock-On: Target enemies behind you.
- Auto-Retargeting: Snaps to the next enemy upon defeat.
- Instant Target Lock/Break: Initiate and break lock-on faster.
- Faster Aim Tracking: Quicker rotation to targets.
"""
short_description = "Customize your Z-Targeting experience!"
authors = [ "BassFace" ]
website_url = "https://github.com/BassFace2761/z-target-suite"
game_id = "mm"
minimum_recomp_version = "1.2.2"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "z_targeting_suite"
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]
additional_files = [ "thumb.dds" ]

[[manifest.config_options]]
id = "immersive_targeting"
name = "Immersive Targeting"
description = """
Removes all visual and sound cues outside of Tatl, making Z-Targeting purely diegetic!
When enabled, you will no longer see the targeting triangles or the yellow hover arrows.
"""
type = "Enum"
options = ["off", "on"]
default = "off"

[[manifest.config_options]]
id = "target_behind"
name = "360-Degree Targeting"
description = """
Allows you to lock onto enemies and objects outside of your line-of-sight.
"""
type = "Enum"
options = ["off", "on"]
default = "on"

[[manifest.config_options]]
id = "tp_auto_retarget"
name = "Auto-Retarget"
description = """
When your current target is defeated, the camera will automatically snap to the next nearest enemy.
"""
type = "Enum"
options = ["off", "on"]
default = "on"

[[manifest.config_options]]
id = "instant_targeting"
name = "Instant Target Lock/Break"
description = """
Removes the short delay when starting or breaking a lock-on.
"""
type = "Enum"
options = ["off", "on"]
default = "on"

[[manifest.config_options]]
id = "faster_aim_tracking"
name = "Faster Aim Tracking"
description = """
Increases the speed that Link rotates and aims at his target.
"""
type = "Enum"
options = ["off", "on"]
default = "on"